[env]
_.python.venv = ".venv"

# Training

[tasks.train]
description = "Train base policy"
run = "lerobot-train --config_path configs/train.yaml"

[tasks.adv-train]
description = "Train advantage policy"
usage = 'arg "<name>"'
run = """
lerobot-train --config_path configs/advantage_train.yaml \
  --job_name={{ usage.name }} \
  --policy.path=reece-omahoney/adv-libero-base \
  --policy.repo_id=reece-omahoney/{{ usage.name }} \
  --policy.fixed_advantage=false \
  --policy.advantage_dropout=0.3 \
"""

[tasks.eval]
description = "Evaluate policy in LIBERO sim"
run = """
lerobot-eval --config_path configs/eval.yaml \
  --policy.path=reece-omahoney/adv-libero-base \
  --policy.device=cuda:1
"""

# Hardware

[tasks.record]
description = "Record demonstrations via teleop"
run = "lerobot-record --config_path configs/record.yaml"

[tasks.play]
description = "Play trained policy on physical arm"
run = "lerobot-record --config_path configs/play.yaml --policy.path=reece-omahoney/smolvla-libero-256"

# Cluster

[tasks.sky]
description = "Launch training on vast.ai via SkyPilot, or exec on a running cluster if given a cluster ID"
usage = 'arg "[cluster_id]"'
run = """
{% if usage.cluster_id %}
sky exec {{ usage.cluster_id }} configs/sky.yaml --env HF_TOKEN --env WANDB_API_KEY
{% else %}
sky launch configs/sky.yaml -y --env HF_TOKEN --env WANDB_API_KEY
{% endif %}
"""

[tasks.sky-ssh]
description = "Launch training via SkyPilot using SSH config, or exec on a running cluster if given a cluster ID"
usage = 'arg "[cluster_id]"'
run = """
{% if usage.cluster_id %}
sky exec {{ usage.cluster_id }} configs/sky-ssh.yaml --env HF_TOKEN --env WANDB_API_KEY
{% else %}
sky launch configs/sky-ssh.yaml -y --env HF_TOKEN --env WANDB_API_KEY
{% endif %}
"""

[tasks.container]
description = "Build Singularity container and upload to cluster"
run = """
singularity build --force --fakeroot container.sif container.def
scp container.sif htc:/data/engs-robotics-ml/kebl6123/distal/container.sif
"""
