[env]
_.python.venv = ".venv"

# Training

[tasks.train]
description = "Train policy"
run = "lerobot-train --config_path configs/advantage_train.yaml"

[tasks.eval]
description = "Evaluate policy in LIBERO sim"
run = "lerobot-eval --config_path configs/eval.yaml --policy.path=reece-omahoney/smolvla-libero-16-chunk"

# Hardware

[tasks.record]
description = "Record demonstrations via teleop"
run = "lerobot-record --config_path configs/record.yaml"

[tasks.play]
description = "Play trained policy on physical arm"
run = "lerobot-record --config_path configs/play.yaml --policy.path=reece-omahoney/smolvla-libero-256"

# Cluster

[tasks.container]
description = "Build Singularity container and upload to cluster"
run = """
singularity build --force --fakeroot container.sif container.def
scp container.sif htc:/data/engs-robotics-ml/kebl6123/distal/container.sif
"""
