[workspace]
authors = ["Reece O'Mahoney <reece.omahoney3@gmail.com>"]
channels = ["conda-forge"]
name = "distal"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
ffmpeg = ">=8.1.1,<9"
imagemagick = ">=7.1.2_21,<8"
