num_workers: 4
batch_size: 64
steps: 40_000
eval_freq: 5000
save_freq: 5000

dataset:
  repo_id: reece-omahoney/libero-10-adv-steps-penalty
  use_imagenet_stats: false

env:
  type: libero
  task: libero_10
  fps: 10
  observation_height: 256
  observation_width: 256

eval:
  n_episodes: 20
  batch_size: 5
  use_async_envs: true

wandb:
  enable: true
  disable_artifact: true
  project: distal
