job_name: smolvla-libero-advantage
num_workers: 8
batch_size: 32
steps: 50_000
eval_freq: 10_000

dataset:
  repo_id: reece-omahoney/libero-10-maha

env:
  type: libero
  task: libero_10
  task_ids: [9]
  fps: 10

policy:
  type: advantage
  repo_id: reece-omahoney/smolvla-libero-advantage
  smolvla_checkpoint: reece-omahoney/smolvla-libero-16-chunk
  stats_repo_id: reece-omahoney/libero
  advantage_dropout: 0.3
  device: cuda
  chunk_size: 16
  n_action_steps: 8
  load_vlm_weights: true
  resize_imgs_with_padding: [256, 256]
  max_state_dim: 8
  max_action_dim: 7

eval:
  n_episodes: 10
  batch_size: 1

wandb:
  enable: true
  disable_artifact: true
  project: distal
