env:
  type: libero
  task: libero_10
  fps: 20
  observation_height: 256
  observation_width: 256

eval:
  n_episodes: 50
  batch_size: 16

policy:
  path: reece-omahoney/pistar-knn-libero
  n_action_steps: 10
  dtype: bfloat16
  device: cuda
