strategy:
  type: episodic
  max_episode_steps: 400
  end_key: e
  discard_key: d
  success_key: s
  failure_key: f

inference:
  type: rtc

robot:
  type: piper
  teleop_mode: false

policy:
  path: reece-omahoney/pi05-remove-pen-lid-2
  n_action_steps: 20

dataset:
  repo_id: reece-omahoney/rollout_remove-pen-lid-2
  single_task: Remove the pen lid
  fps: 20
  streaming_encoding: true
  encoder_threads: 5
  vcodec: auto
  push_to_hub: false

fps: 20
task: Remove the pen lid
use_torch_compile: false
display_data: false
