name: distal-train

resources:
  cloud: ssh
  accelerators: RTX4090:2
  cpus: 31

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
  # MUJOCO_EGL_DEVICE_ID: 0
  SLURM_JOB_ID: 0  # suppress tqdm
  CUDA_VISIBLE_DEVICES: 1
workdir: .

setup: |
  sudo apt-get update && sudo apt-get install -y \
    cmake \
    ffmpeg \
    g++ \
    libegl1 \
    libexpat1 \
    libfontconfig1-dev \
    libgl1 \
    libglvnd0 \
    libmagickwand-dev \
    libopengl0

  curl https://mise.run | sh
  echo 'eval "$($HOME/.local/bin/mise activate bash)"' >> ~/.bashrc
  export PATH="$HOME/.local/bin:$PATH"
  eval "$(mise activate bash)"
  cd ~/sky_workdir
  mise trust

  uv sync

  mkdir ~/.libero
  cat <<EOF > ~/.libero/config.yaml
  assets: $HOME/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./assets
  bddl_files: $HOME/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./bddl_files
  benchmark_root: $HOME/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero
  datasets: $HOME/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/../datasets
  init_states: $HOME/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./init_files
  EOF

  cd ~/sky_workdir
  python ~/sky_workdir/.venv/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py

run: |
  cd ~/sky_workdir
  uv run distal/train_value.py
