name: distal-train

resources:
  cloud: vast
  accelerators: H100:1
  cpus: 16+
  disk_size: 64
  autostop:
    idle_minutes: 10

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl

workdir: .

setup: |
  apt-get update && apt-get install -y libegl1 libosmesa6-dev

  curl https://mise.run | sh
  echo 'eval "$($HOME/.local/bin/mise activate bash)"' >> ~/.bashrc
  export PATH="$HOME/.local/bin:$PATH"
  eval "$(mise activate bash)"
  cd ~/sky_workdir
  mise trust

  uv sync

  mkdir ~/.libero
  cat <<EOF > ~/.libero/config.yaml
  assets: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./assets
  bddl_files: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./bddl_files
  benchmark_root: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero
  datasets: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/../datasets
  init_states: /root/sky_workdir/.venv/lib/python3.12/site-packages/libero/libero/./init_files
  EOF

  cd ~/sky_workdir
  python /root/sky_workdir/.venv/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py

run: |
  cd ~/sky_workdir
  uv run mise run train
