name: distal-train

resources:
  cloud: vast
  accelerators: RTXPRO6000WS
  disk_size: 128
  autostop:
    idle_minutes: 10
    down: true

envs:
  HF_TOKEN:
  WANDB_API_KEY:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
workdir: .

setup: |
  curl -fsSL https://pixi.sh/install.sh | bash
  export PATH="$HOME/.pixi/bin:$PATH"

  cd ~/sky_workdir
  pixi config set --local run-post-link-scripts insecure
  pixi install

  pixi run bash ~/sky_workdir/scripts/setup_libero.sh
  pixi run python ~/sky_workdir/.pixi/envs/default/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py

run: |
  cd ~/sky_workdir
  export LD_LIBRARY_PATH="$HOME/sky_workdir/.pixi/envs/default/lib:$LD_LIBRARY_PATH"

  pixi run python distal/train_pi_star.py
