host: u6jz.aip2.isambard
remote_path: /home/u6jz/reece.u6jz/distal

time: 24
gpu: ""
ngpu: 1
cpus: 72
mem: 1600M
partition: workq

envs:
  - WANDB_API_KEY
  - HF_TOKEN
  - MUJOCO_GL: egl
  - OPENBLAS_NUM_THREADS: 8
  - OMP_NUM_THREADS: 8
  - MKL_NUM_THREADS: 8
  - TORCHINDUCTOR_CACHE_DIR: $HOME/.cache/torchinductor
  - TRITON_CACHE_DIR: $HOME/.cache/triton
  - PATH: $HOME/.local/bin:$HOME/.pixi/bin:$PWD/.pixi/envs/cu126/bin:$PATH
  - LD_LIBRARY_PATH: $PWD/.pixi/envs/cu126/lib:$LD_LIBRARY_PATH
  - PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
command: |-
  module load cuda/12.6
  bash scripts/setup_libero.sh

  pixi run -e cu126 eval
