host: u6jz.aip2.isambard
remote_path: /home/u6jz/reece.u6jz/distal

time: 24
gpu: ""
ngpu: 1
cpus: 72
mem: 1600M
partition: workq

envs:
  - WANDB_API_KEY
  - HF_TOKEN
command: |-
  # modules and env vars
  module load cuda/12.6
  export OPENBLAS_NUM_THREADS=8
  export OMP_NUM_THREADS=8
  export MKL_NUM_THREADS=8
  export PATH="$HOME/.local/bin:$HOME/.pixi/bin:$PWD/.pixi/envs/default/bin:$PATH"

  # install packacges
  uv sync
  pixi install
  export LD_LIBRARY_PATH="$PWD/.pixi/envs/default/lib:$LD_LIBRARY_PATH"

  # run command
  uv run distal/train_value.py
