host: htc
remote_path: /data/engs-robotics-ml/kebl6123/distal
command: >-
  singularity run --nv
  --bind /data/engs-robotics-ml/kebl6123/.cache:/data/engs-robotics-ml/kebl6123/.cache
  --env "WANDB_API_KEY=${WANDB_API_KEY}"
  --env "HF_TOKEN=${HF_TOKEN}"
  --env "PYTHONPATH=/data/engs-robotics-ml/kebl6123/distal:/data/engs-robotics-ml/kebl6123/distal/lerobot_policy_advantage"
  container.sif python distal/train_pi_star.py
time: 12
gpu: h100
ngpu: 1
cpus: 16
mem: 16G
priority: true
dry_run: false
