job_name: adv-libero-base
num_workers: 16
batch_size: 256
steps: 100_000
eval_freq: 10_000

dataset:
  repo_id: lerobot/libero
  use_imagenet_stats: false

env:
  type: libero
  task: libero_10
  fps: 10
  process_isolation: true
  observation_height: 256
  observation_width: 256

# these are overriden when finetuning
policy:
  type: advantage
  fixed_advantage: true
  repo_id: reece-omahoney/adv-libero-base
  device: cuda
  chunk_size: 16
  n_action_steps: 8
  load_vlm_weights: true
  resize_imgs_with_padding: [256, 256]
  max_state_dim: 8
  max_action_dim: 7
  scheduler_decay_steps: 100_000
  compile_model: true

eval:
  n_episodes: 5
  batch_size: 5

wandb:
  enable: true
  disable_artifact: true
  project: distal
