dataset_repo_id: reece-omahoney/libero-10-maha
c_fail: 1000.0
value:
  vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
  expert_width_multiplier: 0.5
  resize_imgs_with_padding: [256, 256]
  max_state_dim: 8
  n_bins: 201
batch_size: 32
total_steps: 50000
output_dir: outputs/value
wandb_project: piper-value
